# Do not keep secrets in the repository,
# instead read values from the environment.
development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: 'ee3af1a61a27f5cc34e5baa7ea5871bee59471e33162c84473254584433e6a708fb06166f7b19d411182fee1eb8006f0401325c20102118ab806b76b71dacacb'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

dev:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
